### ISSUE TITLE
UI feedback on Quantity prefill

### ISSUE THREAD

**Issue by fdesroches** [fdesroches/Premise-UX#62]

**Comment by fdesroches** [comment]
@sloyan to add @lukestclair when he accepts my invitation to join this repo :)

There are some tiny UI niggles I'd like to point out. Thanks!

![quantity-prefill-ui-flow-comment](https://cloud.githubusercontent.com/assets/8029091/5151642/071834a0-7196-11e4-9562-db2678fd60ab.png)

**Comment by LukeStClair** [comment]
Dropdowns should be aligned with what? What style should they have?

Quantity/Size can have room to breathe underneath, but that means the whole
screen will scroll on smaller devices. Is that worth the tradeoff?

Already planning on doing the other stuff -
